kind: Deployment
apiVersion: apps/v1
metadata:
  labels:
    app: edev-ddd-trade
  name: edev-ddd-trade
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: edev-ddd-trade
  template:
    metadata:
      name: edev-ddd-trade
      labels:
        app: edev-ddd-trade
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - edev-ddd-trade
              topologyKey: "kubernetes.io/hostname"
      containers:
      - name: edev-ddd-trade
        image: repository:5000/edev-ddd-trade:<VERSION>
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 500m
            memory: 1000Mi
          requests:
            cpu: 100m
            memory: 300Mi
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: edev-ddd-trade
  name: edev-ddd-trade
  namespace: default
spec:
  ports:
  - port: 8800
    targetPort: 8800
  selector:
    app: edev-ddd-trade
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-edev-trade
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - host: trade
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: edev-ddd-trade
                port:
                  number: 8800